push = false
consolidate-commits = true
pre-release-commit-message = "(cargo-release) Bump version"
tag = false
publish = false
pre-release-replacements = [
    {file="nfpm.yaml", search="version: ", replace="version: {{version}}"}
]