[package]
name = "qmkontext"
version = "0.2.0"
edition = "2021"

[package.metadata.release]
pre-release-replacements = []

[lib]
doctest = false

[dependencies]
chrono = "0.4.31"
crossbeam-channel = "0.5.8"
hidapi = "2.4.1"
tracing = "0.1.39"
